### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by Wouter125** [Wouter125/BottomSheet#19]
I will try to keep a list of fixes that need to be applied here. Feel free to open a PR if you got a fix for some of them;

**Minor**
- [ ] Release fix that solves presenting items from detached view controller
- [ ] Release fix where interaction enabled upTo get's lost after navigating

**Major**
- [ ] Write documentation of how you can attach the sheet on a navigationView stack.
- [ ] Figure out how to handle nested scrollviews (adds support for Lists / NavigationViews)

**Released**
- [x] Resolve bug when content is non-scrollable and UI snaps back to original start position.
- [x] Rename some of the additional properties towards Apple's API.
- [x] Include some properties such as; dragHandle / scrim / content scaling
- [x] Programmatically setting the sheet to a different height is currently broken. -> Due to UIViewRepresentable not passing through my values.
- [x] Replace keyboard hack with something more solid. Now the selected detents break after calling it twice.
- [x] Double check if the additional spacer is still needed (potential fix might be calculating the offset from the bottom of the screen by using `.offset(y: UIScreen.main.bounds.height - translation)`)
- [x] Prevent the preference key reset when keyboard opens up (early return when there are no detents, prevents this issue for now)
- [x] Set default height when there is no selectedDetent configured
- [x] Make the header property optional inside the configuration
- [x] Add out animation when dismissing the sheet.

**Comment by Wouter125** [comment]
Trying to get a release out this week with some of the most critical bugs sorted out and a thorough clean up so that we get a fully stable bottomsheet 2.0.

Will do the small minor improvements and additions after.

**Comment by nitishshreee** [comment]
One of the major issue on how to attach the sheet on a navigationView stack is still not resolved.

**Comment by Wouter125** [comment]
Please see the examples attached with the library. This is using a navigationView where you attach it to toplevel. Not in the view itself. Attaching it to the view itself won't allow for the right z-index to happen since the navigationView is on a different level. Please see the following lines;

https://github.com/Wouter125/BottomSheet/blob/e8057900c967e97a85131fb9d220fa727f520610/Example/BottomSheetExample/ExampleOverview.swift#L66-L124

If the problem persists, please open a new issue with a minimal reproducible example and I'll take a look.
